<?php

function islandora_populator_get_populators() {
  $populators =& drupal_static(__FUNCTION__, array());

  if (empty($populators)) {
    $populators = module_invoke_all('islandora_populator');
    drupal_alter('islandora_populator', $populators);
  }

  return $populators;
}

function islandora_populator_islandora_ingest_steps(array $form_state) {
  $mod_path = drupal_get_path('module', 'islandora_populator');

  $steps = array();

  $populators = islandora_populator_get_populators();
  if (!empty($populators)) {
    $steps['islandora_populator_select'] = array(
      'type' => 'form',
      'weight' => 1,
      'form_id' => 'islandora_populator_select_form',
      'args' => array($populators),
      'file' => "$mod_path/select.form.inc",
    );

    $step_storage = islandora_ingest_form_get_step_storage($form_state, 'islandora_populator_select');
    if (isset($step_storage['selected']) && isset($populators[$step_storage['selected']])) {
      $populator = $populators[$step_storage['selected']];
      $steps['islandora_populator_input'] = array(
        'type' => 'form',
        'weight' => $steps['islandora_populator_select']['weight'] + 1,
        'form_id' => $populator['type'] == 'form' ?
          $populator['form'] :
          'islandora_populator_input_form',
        'args' => array($step_storage['selected'], $populator),
        'file' => "$mod_path/input.form.inc",
      );
    }
  }

  return $steps;
}
